spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 10
          max-interval: 30000
          multiplier: 3.0

queue:
  name: messenger01